#pragma config(Sensor, S1,     leftSensor,     sensorLightActive)
#pragma config(Sensor, S2,     rightSensor,    sensorLightActive)
#pragma config(Sensor, S3,     HTleft,         sensorI2CCustom)
#pragma config(Sensor, S4,     HTright,        sensorI2CCustom)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          grabMotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          waterMotor,    tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "header/hitechnic-colour-v2.h"
#include <include/Init.c>
#include <include/SensorsTools.c>
#include <include/Tools.c>
#include <include/MovementTools.c>
#include <include/TachoPID.c>
#include <include/LinePID.c>
#include <include/Turns.c>
#include <include/Manipulators.c>
#include <include/Route.c>
#include <include/Logic.c>

task main() {
	check_battery();

	datalogOpen(0, 4, false);

	// use this for real speed
	//startTask(speedyBobot, 255);

	//initSensor(&colorRightSensor, HTright, HTCS2_MODE_ACTIVE);
	//initSensor(&colorLeftSensor, HTleft, HTCS2_MODE_ACTIVE);
	//SetModeHitech(&colorLeftSensor, HTCS2_MODE_RAW);
	InitCalibrationNormal();
	InitCalibrationRaw();
	InitMarkerCallibrationRaw();
	InitWashCallibrationRaw();

	NOW_ANGLE = 90;

	setBottle(0, 1);
	setBottle(1, 1);
	startTask(waterUp);
	Rooms();


	//LCDWriteInfoHitechRaw(&colorLeftSensor, &WashInfoRawLeft);
	datalogClose();
}
