#pragma config(Sensor, S1,     leftSensor,     sensorLightActive)
#pragma config(Sensor, S2,     rightSensor,    sensorLightActive)
#pragma config(Sensor, S3,     leftHitech,     sensorI2CHiTechnicColor)
#pragma config(Sensor, S4,     rightHitech,    sensorI2CHiTechnicColor)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          grabMotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          elevatorMotor, tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <include/Init.c>
#include <include/SensorsTools.c>
#include <include/MovementTools.c>
#include <include/TachoPID.c>
#include <include/LinePID.c>
#include <include/Turns.c>
#include <include/Manipulators.c>
#include <include/Route.c>
#include "header/hitechnic-colour-v2.h"

task main() {
	NOW_ANGLE = 180;
	Yellow_room(1, 3);
	BrakeLeftRightMotor(1);
}
